env:
  es2021: true
  node: true
extends:
  - prettier
  - plugin:prettier/recommended
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: .
rules:
  import/extensions:
    - error
    - ignorePackages
    - pattern:
        ts: always
  "@typescript-eslint/indent":
    - off
    - 2
  "@typescript-eslint/quotes":
    - error
    - double
  "@typescript-eslint/semi":
    - error
    - always
  "@typescript-eslint/comma-dangle":
    - error
    - always-multiline
  "@typescript-eslint/space-before-function-paren":
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: semi
        requireLast: true
  "@typescript-eslint/consistent-type-assertions":
    - error
    - assertionStyle: angle-bracket
  "@typescript-eslint/no-import-type-side-effects": error
  "@typescript-eslint/strict-boolean-expressions": error
  "@typescript-eslint/prefer-ts-expect-error": off
  "@typescript-eslint/ban-ts-comment": off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - [internal, parent, sibling, index]
        - unknown
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
