# --------------------------------------------
# File: config/repo.yml
# Desc: 仓库配置文件
# Since: 1.0.0
# --------------------------------------------

# --------------------------------------------
# 仓库配置 - 默认
# --------------------------------------------
default:
  # 仓库名称
  repoName: TeyvatGuide
  # 仓库 ID https://api.github.com/repos/BTMuli/TeyvatGuide
  repoId: 610250275
  # 所有者名称
  ownerName: BTMuli
  # 所有者 ID https://api.github.com/users/BTMuli
  ownerId: 72692909

# --------------------------------------------
# 仓库配置 - TeyvatGuide
# --------------------------------------------
TeyvatGuide:
  repoName: TeyvatGuide
  repoId: 610250275
  ownerName: BTMuli
  ownerId: 72692909
