# --------------------------------------------
# File: config/repo.yml
# Desc: 仓库配置文件
# Since: 1.0.0
# --------------------------------------------

# --------------------------------------------
# 仓库配置 - 默认
# --------------------------------------------
default:
  repoName: defaultRepo
  repoId: 0
  ownerName: BTMuli
  ownerId: 72692909

# --------------------------------------------
# 仓库配置 - TeyvatGuide
# --------------------------------------------
TeyvatGuide:
  repoName: TeyvatGuide
  repoId: 610250275
  ownerName: BTMuli
  ownerId: 72692909
